import info
from helpers.database.database import Database

db = Database(info.mongodb+srv://Erichdaniken:Erichdaniken@cluster0.tf4rj.mongodb.net/myFirstDatabase?retryWrites=true&w=majority, info.1BVtsOIsBu0BihEEghJO6JHCUFCtx4-X-gg71s2uwxNvDZRMFJ3n2gT2U-AbEkMCcmF6uk3t3ZU5o3HvKEQwZRdKtVyS3rLRk8pU4SYJIvDp1PCeDZx8DgEQ1ctEbG0cVhtLpNaNyTiXW2jDXHwNVj8QlLbNkN6fCtlyTpIZdsR8btC513Nu_l2hAYkwx2pwDtLJZSUOsvnxkZyIxRQrsoYVthn_FS7MPHEmXnzI5P6LJZdJ2QC-vUJM5-A5rSxznG3EkhtGYjG3NoSIIs8y1XFWzRTD_Pvw8wkVrvFRicMZN_BRp9iGCkd1IG46VZghA8zA_yf4zfzfToldMuQXOEXIrc-ksxx0=)
